services:
  cortex-frontend:
    build:
      context: ./CortexFrontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5214/api
    container_name: cortex-frontend
    ports:
      - "4173:80"
    depends_on:
      - cortex-api

  cortex-api:
    build:
      context: ./CortexBackend
      dockerfile: Dockerfile
    container_name: cortex-api
    ports:
      - "5214:8080"
    depends_on:
      - cortex-sql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CortexDb=Server=cortex-sql;Database=CortexDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False;

  cortex-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cortex-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - cortex_sql_data:/var/opt/mssql

volumes:
  cortex_sql_data:
